[project]
authors = ["Alex Morris <alex@arraywaves.dev>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Extract media from PDF files"
name = "pdf-extract"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
pdf2image = ">=1.17.0,<2"
pdfplumber = ">=0.9.0,<0.10"
max = ">=24.5.0,<25"
